### ISSUE TITLE
Forgotten password view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#10]
**Description:**

As a user, I would like to have a way to reset my password when i forget it.

**Tasks**

- [x] Create page for password reset who matches the figma mockup
- [x] Dynamic hide and see password
- [ ] Send the new passwords to the backend
- [ ] Get the answer of the backend (if the 2 passwords matches)
- [ ] If valid show the login page
- [ ] If Invalid display error message

**Requirements:**
- none
