### ISSUE TITLE
View for the home page

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#14]
**Description:**

As a user, I would like to have a home page with my classroom and some popular decks

**Tasks**

- [ ] Create home page according to figma
- [ ] Clicking on a popular deck send you to the page with details about this deck
- [ ] Clicking on the profile picture send you to your profile page
- [ ] Clicking on "My classroom" send you to a page with all your classrooms

**Requirements:**
- #17
