### ISSUE TITLE
Classroom creation view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#15]
**Description:**

As a user, I would like to be able to create a classroom

**Tasks**

- [x] Implements a page for creating a new classroom.
- [ ] Validate data with the backend (name must be unique)
- [ ] If creation is valid redirect to "my classrooms"
- [ ] If invalid show error message.

**Requirements:**
- none
