### ISSUE TITLE
Classroom edit view (if you are the creator of the room you can edit it otherwise its just a detail page)

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#16]
**Description:**

As a user, I would like to manage my classroom (add new user, set to public/private, change user right for the classroom).

**Tasks**

- [ ] Create page for classroom according to figma
- [ ] Change visibility (public or private)
- [ ] Add or delete users
- [ ] Change right of users (reading or writing)

**Requirements:**
- none

**Comment by nicrausaz** [comment]
Done in #80
