### ISSUE TITLE
Create deck view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#19]
**Description:**

As a user, I would like to be able to create a deck of card.

**Tasks**

- [x] Page for creating a deck see figma for mockup.
- [ ] Send the informations to the backend
- [ ] Get the answer of the backend (valid / invalid)
- [ ] If valid show the classroom page that contains the deck
- [ ] If Invalid display error message

**Requirements:**
- none

**Comment by Lazzzer** [comment]
Done with #41
