### ISSUE TITLE
Display deck

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#20]
**Description:**

As a user, I would like to be able to see the entire deck and have some info on it.

**Tasks**

- [ ] Page that display all the decks inside of a classroom.
- [ ] User must have access to the classroom to see the page.
- [ ] if the user is the creator he can edit the deck on that page
- [ ] Buttons for upvote/downvote (user can only vote once)

**Requirements:**
- none
