### ISSUE TITLE
Create card view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#21]
**Description:**

As a user, I would like to create a card inside the deck so i can learn.

**Tasks**

- [x] Page for creating card machting the mockup on figma.
- [x] Send informations to the backend
- [x] Get the response (valid/invalid)
- [x] Show deck page if valid
- [x] Display error message if invalid

**Requirements:**
- #20
