### ISSUE TITLE
Display card view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#22]
**Description:**

As a user, I would like to have page that shows a revision card with a question and an answer

**Tasks**

- [x] Page that matches the mockup.
- [x] User can click on the card to see the answer.
- [x] Click on the "next" or "previous" button to change card.
- [x] Button to signal the card
- [ ] Get cards from backend with author name and deck's name
- [ ] Send signalement to backend

**Requirements:**
- none
