### ISSUE TITLE
User register view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#6]
**Description:**

As a user, I would like to be able to create an account.

**Tasks**

- [x] Create page who matches the figma mockup
- [x] Send all the informations of the user to the backend
- [ ] Get the answer of the backend (valid or which filed is invalid)
- [ ] If invalid show an error message on the field with the error.
- [ ] If valid ask for the code sent in email

**Requirements:**
- none
