### ISSUE TITLE
User log in view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#7]
**Description:**

As a user, I would like to be able to log in to my account.

**Tasks**

- [x] Create page who matches the figma mockup
- [x] Send the informations to the backend
- [x] Get the answer of the backend
- [x] If valid show the home page.
- [x] If Invalid display error message

**Requirements:**
- #6
