### ISSUE TITLE
Edit profile view

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/application#8]
**Description:**

As a user, I would like to be able to log in to edit my informations such as my name or password.

**Tasks**

- [x] Create page for profile editting who matches the figma mockup
- [ ] Retrieve user profile information and fill inputs and image
- [ ] Send the new informations to the backend
- [ ] Get the answer of the backend (valid / invalid)
- [ ] If valid show the profile page
- [ ] If Invalid display error message

**Requirements:**
- none
